#
# .-'_.---._'-.
# ||####|(__)||   Protect your secrets, protect your business.
#   \\()|##//       Secure your sensitive data with Aegis.
#    \\ |#//                  <aegis.z2h.dev>
#     .\_/.
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: aegis-workload-demo
  namespace: default
  labels:
    app.kubernetes.io/name: aegis-workload-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: aegis-workload-demo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: aegis-workload-demo
    spec:
      serviceAccountName: aegis-workload-demo
      containers:
        - name: main
          image: z2hdev/aegis-workload-demo-using-sidecar:0.7.4
          volumeMounts:
          # `main` shares this volume with `sidecar`.
          - mountPath: /opt/aegis
            name: aegis-secrets-volume
        - name: sidecar
          image: z2hdev/aegis-sidecar:0.7.4
          volumeMounts:
          # /opt/aegis/secrets.json is the place the secrets will be at.
          # As of now, this is not configurable. Once the MVP is complete,
          # weâ€™ll work on making Aegis more flexible and add more configuration
          # options.
          - mountPath: /opt/aegis
            name: aegis-secrets-volume
          # Volume mount for SPIRE unix domain socket.
          - name: spire-agent-socket
            mountPath: /spire-agent-socket
            readOnly: true
          env:
          # Required to fetch SVIDs to establish mTLS.
          # go-spiffe internally uses this.
          - name: SPIFFE_ENDPOINT_SOCKET
            value: unix:///spire-agent-socket/agent.sock
      volumes:
      # A memory-backed volume is recommended (but not required) to keep
      # the secrets. The secrets can be stored in any kind of volume.
      - name: aegis-secrets-volume
        emptyDir:
          medium: Memory
      # SPIRE needs this.
      - name: spire-agent-socket
        hostPath:
          path: /run/spire/sockets
          type: Directory
