#
# .-'_.---._'-.
# ||####|(__)||   Protect your secrets, protect your business.
#   \\()|##//       Secure your sensitive data with Aegis.
#    \\ |#//                  <aegis.z2h.dev>
#     .\_/.
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: aegis-workload-demo
  namespace: default
  labels:
    app.kubernetes.io/name: aegis-workload-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: aegis-workload-demo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: aegis-workload-demo
    spec:
      serviceAccountName: aegis-workload-demo
      containers:
      - name: main
        image: z2hdev/aegis-workload-demo-using-sidecar:0.12.55
        volumeMounts:
        # `main` shares this volume with `sidecar`.
        - mountPath: /opt/aegis
          name: aegis-secrets-volume
        #
        # Resource allocation will highly-depend on the system.
        # Benchmark your deployment, monitor your resource utilization, and
        # adjust these values accordingly.
        # resources:
        #  requests:
        #    memory: "128Mi"
        #    cpu: "250m"
        #  limits:
        #    memory: "128Mi"
        #    # We recommend “NOT” setting a CPU limit.
        #    # As long as you have configured your CPU “requests” correctly,
        #    # everything would work fine.
        #
      - name: sidecar
        image: z2hdev/aegis-sidecar:0.12.55
        volumeMounts:
        # /opt/aegis/secrets.json is the place the secrets will be at.
        # As of now, this is not configurable. Once the MVP is complete,
        # we’ll work on making Aegis more flexible and add more configuration
        # options.
        - mountPath: /opt/aegis
          name: aegis-secrets-volume
        # Volume mount for SPIRE unix domain socket.
        - name: spire-agent-socket
          mountPath: /spire-agent-socket
          readOnly: true
        #
        # You can configure this workload by providing environment variables.
        #
        # See https://aegis.z2h.dev/docs/configuration for more information about
        # these environment variables.
        #
        # When you don’t explicitly provide env vars here, Aegis Safe will assume
        # the default values outlined in the given link above.
        #
        env:
        - name: SPIFFE_ENDPOINT_SOCKET
          value: "unix:///spire-agent-socket/agent.sock"
        - name: AEGIS_LOG_LEVEL
          value: "6"
        - name: AEGIS_WORKLOAD_SVID_PREFIX
          value: "spiffe://aegis.z2h.dev/workload/"
        - name: AEGIS_SAFE_SVID_PREFIX
          value: "spiffe://aegis.z2h.dev/workload/aegis-safe/ns/aegis-system/sa/aegis-safe/n/"
        - name: AEGIS_SIDECAR_POLL_INTERVAL
          value: "20000"
        - name: AEGIS_SIDECAR_MAX_POLL_INTERVAL
          value: "300000"
        - name: AEGIS_SIDECAR_EXPONENTIAL_BACKOFF_MULTIPLIER
          value: "2"
        - name: AEGIS_SIDECAR_SUCCESS_THRESHOLD
          value: "3"
        - name: AEGIS_SIDECAR_ERROR_THRESHOLD
          value: "2"
        #
        # Resource allocation will highly-depend on the system.
        # Benchmark your deployment, monitor your resource utilization, and
        # adjust these values accordingly.
        #
        # resources:
        #  requests:
        #    memory: "128Mi"
        #    cpu: "250m"
        #  limits:
        #    memory: "128Mi"
        #    # We recommend “NOT” setting a CPU limit.
        #    # As long as you have configured your CPU “requests” correctly,
        #    # everything would work fine.
        #
      volumes:
      # A memory-backed volume is recommended (but not required) to keep
      # the secrets. The secrets can be stored in any kind of volume.
      - name: aegis-secrets-volume
        emptyDir:
          medium: Memory
      # Using SPIFFE CSI Driver to bind to the SPIRE Agent Socket
      # ref: https://github.com/spiffe/spiffe-csi
      - name: spire-agent-socket
        csi:
          driver: "csi.spiffe.io"
          readOnly: true
