#
# .-'_.---._'-.
# ||####|(__)||   Protect your secrets, protect your business.
#   \\()|##//       Secure your sensitive data with Aegis.
#    \\ |#//                    <aegis.ist>
#     .\_/.
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: aegis-workload-demo
  namespace: default
  labels:
    app.kubernetes.io/name: aegis-workload-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: aegis-workload-demo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: aegis-workload-demo
    spec:
      serviceAccountName: aegis-workload-demo
      containers:
      - name: main
        image: z2hdev/aegis-workload-demo-using-sdk:0.13.0
        volumeMounts:
        # Volume mount for SPIRE unix domain socket.
        - name: spire-agent-socket
          mountPath: /spire-agent-socket
          readOnly: true
        #
        # You can configure this workload by providing environment variables.
        #
        # See https://aegis.ist/docs/configuration for more information
        # about these environment variables.
        #
        # When you donâ€™t explicitly provide env vars here, Aegis Safe will
        # assume the default values outlined in the given link above.
        #
        env:
        - name: SPIFFE_ENDPOINT_SOCKET
          value: "unix:///spire-agent-socket/agent.sock"
        - name: AEGIS_LOG_LEVEL
          value: "6"
        - name: AEGIS_WORKLOAD_SVID_PREFIX
          value: "spiffe://aegis.ist/workload/"
        - name: AEGIS_SAFE_SVID_PREFIX
          value: "spiffe://aegis.ist/workload/aegis-safe/ns/aegis-system/sa/aegis-safe/n/"
      volumes:
      # Using SPIFFE CSI Driver to bind to the SPIRE Agent Socket
      # ref: https://github.com/spiffe/spiffe-csi
      - name: spire-agent-socket
        csi:
          driver: "csi.spiffe.io"
          readOnly: true
