#
# .-'_.---._'-.
# ||####|(__)||   Protect your secrets, protect your business.
#   \\()|##//       Secure your sensitive data with Aegis.
#    \\ |#//                  <aegis.ist>
#     .\_/.
#

apiVersion: v1
kind: ServiceAccount
metadata:
  name: aegis-sentinel
  namespace: aegis-system
automountServiceAccountToken: false
