#
# .-'_.---._'-.
# ||####|(__)||   Protect your secrets, protect your business.
#   \\()|##//       Secure your sensitive data with Aegis.
#    \\ |#//                  <aegis.z2h.dev>
#     .\_/.
#

apiVersion: v1
kind: Secret
metadata:
  # The string after `aegis-secret-` must match the workloadâ€™s name.
  # For example, this is an Aegis-managed secret for `aegis-workload-demo`
  # with the SPIFFE ID
  # `"spiffe://aegis.z2h.dev/workload/aegis-workload-demo\
  #  /ns/{{ .PodMeta.Namespace }}\
  #  /sa/{{ .PodSpec.ServiceAccountName }}\
  #  /n/{{ .PodMeta.Name }}"`
  name: aegis-secret-aegis-workload-demo
  namespace: default
type: Opaque