#
# .-'_.---._'-.
# ||####|(__)||   Protect your secrets, protect your business.
#   \\()|##//       Secure your sensitive data with Aegis.
#    \\ |#//                  <aegis.z2h.dev>
#     .\_/.
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  labels:
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
      annotations:
        # To automatically inject sidecar instead of manually creating one.
        aegis-inject-sidecar: "false"
        # The name the workload will be referred.
        # Admin API will use this name to register secrets for this workload.
        aegis-workload-key: aegis-workload-demo
    spec:
      containers:
        - name: main
          image: z2hdev/aegis-workload-demo:0.5.0
          volumeMounts:
          - mountPath: /opt/aegis
            name: aegis-secrets-volume

        - name: sidecar
          image: z2hdev/aegis-sidecar:0.5.0
          ports:
          - containerPort: 8039
          volumeMounts:

          # /opt/aegis/secrets.json is the place the secrets will be at.
          # As of now, this is not configurable. Once the MVP is complete,
          # weâ€™ll work on making Aegis more flexible and add more configuration
          # options.
          - mountPath: /opt/aegis
            name: aegis-secrets-volume

          env:
          - name: AEGIS_APP_NAME
            value: "aegis-sidecar"

          # The port that sidecar webhook is listening at.
          # Right now, it is not configurable.
          - name: AEGIS_PORT
            value: ":8039"

      # A memory-backed volume is recommended (but not required) to keep
      # the secrets. The secrets can be stored in any kind of volume.
      volumes:
        - name: aegis-secrets-volume
          emptyDir:
            medium: Memory